version: '3.2'

services:
  back:
    container_name: demo-back-end
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    volumes:
      - ./back-end/:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CON_STR=${DB_CON_STR}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CHOKIDAR_USEPOLLING=true
  front:
    container_name: demo-front-end
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
      - /usr/app/build
    depends_on:
      - back
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}